export const defaultTheme = {
  basicTextColor: "#333333",
  buttonColor: "#fc9b27",
  buttonHoverActiveColor: "#fc7427",
  farmFeatureColor: "#e1edce",
  shopFeatureColor: "#f8ddd7",
  activeTabColor: "#88aa4d",
  bgBasicColor: "#d8ecfe",
  bgLightColor: "#f6f6f6",
  bgColorGray: "#f7f7f7",
  colorWhite: "#ffffff",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSize: "18px",
  lineHeight: "1.5",
  pageWidth: "1280px",
  pagePadding: "90px",
  indent: "20px",
};
